/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomNumberInputElement {
        "class": string;
        "disabled": boolean;
        "name": string;
        "readonly": boolean;
        "type": string;
        "value": string|number;
    }
}
declare global {
    interface HTMLCustomNumberInputElementElement extends Components.CustomNumberInputElement, HTMLStencilElement {
    }
    var HTMLCustomNumberInputElementElement: {
        prototype: HTMLCustomNumberInputElementElement;
        new (): HTMLCustomNumberInputElementElement;
    };
    interface HTMLElementTagNameMap {
        "custom-number-input-element": HTMLCustomNumberInputElementElement;
    }
}
declare namespace LocalJSX {
    interface CustomNumberInputElement {
        "class"?: string;
        "disabled"?: boolean;
        "name"?: string;
        "readonly"?: boolean;
        "type"?: string;
        "value"?: string|number;
    }
    interface IntrinsicElements {
        "custom-number-input-element": CustomNumberInputElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-number-input-element": LocalJSX.CustomNumberInputElement & JSXBase.HTMLAttributes<HTMLCustomNumberInputElementElement>;
        }
    }
}
